### ISSUE TITLE
Exposing and Accessing ports from the host machine

### ISSUE THREAD

**Issue by LordRahl90** [jeremyhuiskamp/golang-docker-scratch#1]
How do you cater for exposing ports and accessing ports from the outside.

**Comment by jeremyhuiskamp** [comment]
The same way you do any other time you're using docker: https://docs.docker.com/config/containers/container-networking/

This recipe should have no effect on any of that.

**Comment by LordRahl90** [comment]
Issue is when i tried to run d image, i couldnt access it via the exposed port. Hence the question.

But when i created a docker-compose file and use the image with the exposed port, it worked quiet well...

**Comment by jeremyhuiskamp** [comment]
This recipe does not expose any ports.  If you added one, it still wouldn't do anything because the application inside doesn't listen on any ports, and exits almost immediately.

What exactly are you trying to do?

**Comment by LordRahl90** [comment]
I was trying to generate a small docker image with golang but i needed the port exposed because it will be API based.

So when I exposed PORT with the scratch image, and executed with -p flag, I couldnt connect. So I decide to put it in a docker-compose file then define the port from there. It worked like a charm.
Thanks.

**Comment by jeremyhuiskamp** [comment]
I'm sorry, that's not related to this project at all and this is not the place to ask question about ports.  Please see the link above to learn more about it.
