### ISSUE TITLE
Consider building Go binaries with "timetzdata" build tag

### ISSUE THREAD

**Issue by ivy** [jeremyhuiskamp/golang-docker-scratch#2]
Thank you for the lovely project! I've found it super informative. 😄

While diving into some of the latest Go internals, I discovered [`src/time/embed.go`](https://golang.org/src/time/embed.go) bundles a prebuilt `zoneinfo.zip` file directly into the built binary. The `timetzdata` build tag just needs to be present to enable this behavior and overall, I'd say it seems like a better option.

I imagine a single `zoneinfo.zip` file specified through the `ZONEINFO` environment variable is still the best option for a developer who wishes to distribute *multiple* binaries within a single Docker image.

**Comment by jeremyhuiskamp** [comment]
Thanks for pointing this out @ivy!  That's definitely a nicer solution, so I've made it the default and kept the old implementation on the side as an option.

**Comment by jeremyhuiskamp** [comment]
Interestingly, the increase in size in the executable is only about 400k, while the zoneinfo.zip from alpine is about 1800k.  As far as I can tell, the difference is that go includes only posix zones.  https://askubuntu.com/questions/34925/organization-of-zoneinfo-folder contains some interesting explanations.
